### ISSUE TITLE
Picacomic: Not able to download chapters

### ISSUE THREAD

**Issue by zzh4n** [tachiyomiorg/tachiyomi-extensions#11481]
### Source information

Picacomic 1.2.1

### Steps to reproduce

1. Select a comic on `Picacomic`
2. Click the `Download Icon` for the chapter

### Expected behavior

Downloaded successfully without problems.

### Actual behavior

Download fails with red warning icon.

### Tachiyomi version

0.13.3

### Android version

Android 12

### Other details

I checked the storage directory. There are files with `_tmp` suffix in there. The files inside the folder are intact, there seems to be a problem with the renaming.

I've tried downloading a lot of manga, but this problem only occurs when downloading manga from `Picacomic`. So I think it might be a problem with the `Picacomic` extension.

This problem has existed since I started using Tachiyomi, and it has not been solved until now.

I also tried to get the crash log, hope it helps.

_- from Google Translate (Original language: Chinese)_

```
--------- beginning of main
04-16 07:15:56.372  7473 20790 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
04-16 07:15:56.372  7473 20792 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
04-16 07:15:56.372  7473 20792 E chromium: [ERROR:simple_index_file.cc(577)] Could not reconstruct index from disk
04-16 07:15:56.372  7473 20790 E chromium: [ERROR:simple_index_file.cc(577)] Could not reconstruct index from disk
04-16 07:17:08.622 21327 21327 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-16 07:17:08.623 21327 21327 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-16 07:17:09.382 21327 21427 E SQLiteLog: (284) automatic index on C(manga_id)
04-16 07:17:09.382 21327 21427 E SQLiteLog: (284) automatic index on R(manga_id)
04-16 07:17:09.382 21327 21427 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-16 07:19:42.967 22965 22965 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-16 07:19:42.968 22965 22965 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-16 07:19:43.602 22965 23042 E SQLiteLog: (284) automatic index on C(manga_id)
04-16 07:19:43.602 22965 23042 E SQLiteLog: (284) automatic index on R(manga_id)
04-16 07:19:43.602 22965 23042 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-16 07:21:10.616 23967 23967 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-16 07:21:10.617 23967 23967 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-16 07:21:11.248 23967 24041 E SQLiteLog: (284) automatic index on C(manga_id)
04-16 07:21:11.248 23967 24041 E SQLiteLog: (284) automatic index on R(manga_id)
04-16 07:21:11.248 23967 24041 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.3 (standard, 28522f4, 79, 2022-04-15T20:39Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.T970ZCU2CVA6
Device brand: samsung
Device manufacturer: samsung
Device name: gts7xlwifi
Device model: SM-T970
Device product name: gts7xlwifizc
```

```
--------- beginning of main
04-16 07:42:42.084 23967 23967 E RealImageLoader: coil.request.NullRequestDataException: The request's data is null.
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at coil.RealImageLoader.access$executeMain(RealImageLoader.kt:56)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at coil.RealImageLoader$enqueue$job$1.invokeSuspend(RealImageLoader.kt:4)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:23)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:3)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:1)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:10)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:1)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:5)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.BuildersKt.async(Unknown Source:1)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:3)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at kotlinx.coroutines.BuildersKt.async$default(Unknown Source:1)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at coil.RealImageLoader.enqueue(RealImageLoader.kt:1)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at eu.kanade.tachiyomi.ui.browse.migration.sources.SourceHolder$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:9)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at android.os.Handler.handleCallback(Handler.java:938)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at android.os.Handler.dispatchMessage(Handler.java:99)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at android.os.Looper.loopOnce(Looper.java:226)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at android.os.Looper.loop(Looper.java:313)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at android.app.ActivityThread.main(ActivityThread.java:8633)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at java.lang.reflect.Method.invoke(Native Method)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
04-16 07:42:42.084 23967 23967 E RealImageLoader:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
04-16 07:42:53.736 23967 23967 E RealImageLoader: coil.request.NullRequestDataException: The request's data is null.
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at coil.RealImageLoader.access$executeMain(RealImageLoader.kt:56)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at coil.RealImageLoader$enqueue$job$1.invokeSuspend(RealImageLoader.kt:4)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:23)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:3)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:1)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:10)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:1)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:5)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.BuildersKt.async(Unknown Source:1)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:3)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at kotlinx.coroutines.BuildersKt.async$default(Unknown Source:1)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at coil.RealImageLoader.enqueue(RealImageLoader.kt:1)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at eu.kanade.tachiyomi.ui.browse.migration.sources.SourceHolder$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:9)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at android.os.Handler.handleCallback(Handler.java:938)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at android.os.Handler.dispatchMessage(Handler.java:99)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at android.os.Looper.loopOnce(Looper.java:226)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at android.os.Looper.loop(Looper.java:313)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at android.app.ActivityThread.main(ActivityThread.java:8633)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at java.lang.reflect.Method.invoke(Native Method)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
04-16 07:42:53.736 23967 23967 E RealImageLoader:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
04-16 07:43:06.652 23967 23978 E System  : Uncaught exception thrown by finalizer
04-16 07:43:06.652 23967 23978 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
04-16 07:43:06.652 23967 23978 E System  :  at dalvik.system.DexFile.finalize(DexFile.java:353)
04-16 07:43:06.652 23967 23978 E System  :  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
04-16 07:43:06.652 23967 23978 E System  :  at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
04-16 07:43:06.652 23967 23978 E System  :  at java.lang.Daemons$Daemon.run(Daemons.java:139)
04-16 07:43:06.652 23967 23978 E System  :  at java.lang.Thread.run(Thread.java:920)
04-16 07:46:13.787 10746 10746 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-16 07:46:13.788 10746 10746 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-16 07:49:46.668 13454 13454 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-16 07:49:46.669 13454 13454 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-16 07:49:47.352 13454 13526 E SQLiteLog: (284) automatic index on C(manga_id)
04-16 07:49:47.352 13454 13526 E SQLiteLog: (284) automatic index on R(manga_id)
04-16 07:49:47.352 13454 13526 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-16 07:50:12.446 13937 13937 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-16 07:50:12.449 13937 13937 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-16 07:50:13.070 13937 14016 E SQLiteLog: (284) automatic index on C(manga_id)
04-16 07:50:13.070 13937 14016 E SQLiteLog: (284) automatic index on R(manga_id)
04-16 07:50:13.070 13937 14016 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-16 07:50:22.424 14257 14257 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-16 07:50:22.425 14257 14257 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-16 07:50:23.043 14257 14334 E SQLiteLog: (284) automatic index on C(manga_id)
04-16 07:50:23.043 14257 14334 E SQLiteLog: (284) automatic index on R(manga_id)
04-16 07:50:23.043 14257 14334 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.3 (standard, 28522f4, 79, 2022-04-15T20:39Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.T970ZCU2CVA6
Device brand: samsung
Device manufacturer: samsung
Device name: gts7xlwifi
Device model: SM-T970
Device product name: gts7xlwifizc
```

![](https://user-images.githubusercontent.com/58251004/163653882-be6df53e-7d71-439f-a1bf-ad4b85447e9f.jpg)
![](https://user-images.githubusercontent.com/58251004/163653889-7bffee83-8bbc-467a-bfb3-67906ce40e7c.jpg)
![](https://user-images.githubusercontent.com/58251004/163653892-19a1ed92-230c-4634-8069-caebc91d5027.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
I found the problem. The page numbers of pages after 40 are wrong, so they can not be downloaded.
