### ISSUE TITLE
Blogtruyen: The image couldn't be loaded

### ISSUE THREAD

**Issue by MankMeo** [tachiyomiorg/tachiyomi-extensions#13901]
### Source information and language

Blogtruyen 1.3.9 (Vietnamese)

### Steps to reproduce

1. Open Tachiyomi
2. Go to "Blogtruyen" extension and read some mangas
3. The image couldn't be loaded

![Screenshot_2022-10-18-13-58-09-532_eu kanade tachiyomi](https://user-images.githubusercontent.com/44147551/196361450-82815a16-172d-4b74-8456-b2eb429c07f9.jpg)

### Expected behavior

The image should be shown

### Actual behavior

The bug happened

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

Log bug:
--------- beginning of system
--------- beginning of main
10-18 13:11:21.860 32655 32655 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 13:11:22.499 32655 32691 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 13:11:22.499 32655 32691 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:11:22.500 32655 32691 E Perf    : Fail to get file list oat
10-18 13:11:22.500 32655 32691 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:11:23.227 32655   430 E SQLiteLog: (283) recovered 33 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-18 13:11:23.282 32655   431 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 13:11:23.282 32655   431 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 13:11:23.283 32655   431 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 13:11:25.718 32655 32692 E BufferQueueProducer: [unnamed-32655-0] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:11:25.718 32655 32692 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:37:35.436  5420  5420 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 13:37:36.057  5420  5478 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 13:37:36.057  5420  5478 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:37:36.057  5420  5478 E Perf    : Fail to get file list oat
10-18 13:37:36.058  5420  5478 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:37:36.756  5420  5544 E SQLiteLog: (283) recovered 3 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-18 13:37:36.785  5420  5544 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 13:37:36.785  5420  5544 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 13:37:36.785  5420  5544 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 13:42:56.003  5420  5479 E BufferQueueProducer: [unnamed-5420-0] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:42:56.004  5420  5479 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:46:30.001  6551  6551 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 13:46:30.315  6551  6581 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 13:46:30.316  6551  6581 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:46:30.317  6551  6581 E Perf    : Fail to get file list oat
10-18 13:46:30.317  6551  6581 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:46:30.890  6551  6649 E SQLiteLog: (283) recovered 3 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-18 13:46:30.907  6551  6649 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 13:46:30.907  6551  6649 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 13:46:30.907  6551  6649 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 13:46:32.897  6551  6582 E BufferQueueProducer: [unnamed-6551-0] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:46:32.897  6551  6582 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:46:36.804  6551  6582 E BufferQueueProducer: [unnamed-6551-1] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:46:36.804  6551  6582 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:46:38.053  6551  6744 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
10-18 13:46:38.053  6551  6744 E chromium: [ERROR:simple_index_file.cc(617)] Could not reconstruct index from disk
10-18 13:47:29.180  6551  6582 E BufferQueueProducer: [unnamed-6551-2] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:47:29.180  6551  6582 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:47:30.499  6551  6582 E BufferQueueProducer: [unnamed-6551-3] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:47:30.499  6551  6582 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:47:31.401  6551  6582 E BufferQueueProducer: [unnamed-6551-4] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:47:31.401  6551  6582 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:47:32.459  6551  6582 E BufferQueueProducer: [unnamed-6551-5] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:47:32.459  6551  6582 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:51:32.739  7433  7433 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 13:51:33.051  7433  7464 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 13:51:33.052  7433  7464 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:51:33.052  7433  7464 E Perf    : Fail to get file list oat
10-18 13:51:33.052  7433  7464 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:51:33.686  7433  7534 E SQLiteLog: (283) recovered 12 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-18 13:51:33.707  7433  7534 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 13:51:33.707  7433  7534 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 13:51:33.708  7433  7534 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 13:51:36.985  7433  7466 E BufferQueueProducer: [unnamed-7433-0] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:51:36.985  7433  7466 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:56:10.125  8288  8288 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 13:56:10.465  8288  8319 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 13:56:10.465  8288  8319 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:56:10.466  8288  8319 E Perf    : Fail to get file list oat
10-18 13:56:10.466  8288  8319 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:56:11.103  8288  8387 E SQLiteLog: (283) recovered 3 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-18 13:56:11.134  8288  8387 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 13:56:11.134  8288  8387 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 13:56:11.134  8288  8387 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 13:56:25.169  8539  8539 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 13:56:25.498  8539  8571 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 13:56:25.499  8539  8571 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:56:25.499  8539  8571 E Perf    : Fail to get file list oat
10-18 13:56:25.499  8539  8571 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:56:26.079  8539  8639 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 13:56:26.080  8539  8639 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 13:56:26.080  8539  8639 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 13:57:01.918  8539  8572 E BufferQueueProducer: [unnamed-8539-0] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:57:01.918  8539  8572 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:57:17.773  8539  8572 E BufferQueueProducer: [unnamed-8539-1] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:57:17.773  8539  8572 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:57:25.037  8889  8889 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 13:57:25.364  8889  8921 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 13:57:25.365  8889  8921 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:57:25.365  8889  8921 E Perf    : Fail to get file list oat
10-18 13:57:25.365  8889  8921 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 13:57:25.948  8889  8988 E SQLiteLog: (283) recovered 378 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-18 13:57:25.993  8889  8988 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 13:57:25.993  8889  8988 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 13:57:25.993  8889  8988 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 13:57:28.754  8889  8922 E BufferQueueProducer: [unnamed-8889-0] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:57:28.754  8889  8922 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:57:32.290  8889  8922 E BufferQueueProducer: [unnamed-8889-1] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:57:32.290  8889  8922 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 13:58:07.041  8889  8922 E BufferQueueProducer: [unnamed-8889-2] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 13:58:07.041  8889  8922 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 14:00:21.304 10688 10688 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 14:00:21.706 10688 10720 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 14:00:21.707 10688 10720 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 14:00:21.707 10688 10720 E Perf    : Fail to get file list oat
10-18 14:00:21.707 10688 10720 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 14:00:22.390 10688 10789 E SQLiteLog: (283) recovered 7 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-18 14:00:22.407 10688 10789 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 14:00:22.408 10688 10789 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 14:00:22.408 10688 10789 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 14:02:27.789 11936 11936 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 14:02:28.210 11936 11967 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 14:02:28.210 11936 11967 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 14:02:28.211 11936 11967 E Perf    : Fail to get file list oat
10-18 14:02:28.211 11936 11967 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 14:02:28.942 11936 12039 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 14:02:28.942 11936 12039 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 14:02:28.942 11936 12039 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-18 14:03:02.443 11936 11969 E BufferQueueProducer: [unnamed-11936-0] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
10-18 14:03:02.443 11936 11969 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
10-18 14:03:02.668 11936 11950 E System  : Uncaught exception thrown by finalizer
10-18 14:03:02.669 11936 11950 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
10-18 14:03:02.669 11936 11950 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:351)
10-18 14:03:02.669 11936 11950 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
10-18 14:03:02.669 11936 11950 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
10-18 14:03:02.669 11936 11950 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
10-18 14:03:02.669 11936 11950 E System  : 	at java.lang.Thread.run(Thread.java:919)
10-18 14:08:10.889 14875 14875 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-18 14:08:11.264 14875 14907 E Perf    : Fail to get file list eu.kanade.tachiyomi
10-18 14:08:11.264 14875 14907 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 14:08:11.264 14875 14907 E Perf    : Fail to get file list oat
10-18 14:08:11.265 14875 14907 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
10-18 14:08:11.904 14875 14974 E SQLiteLog: (283) recovered 3 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-18 14:08:11.921 14875 14974 E SQLiteLog: (284) automatic index on C(manga_id)
10-18 14:08:11.921 14875 14974 E SQLiteLog: (284) automatic index on R(manga_id)
10-18 14:08:11.921 14875 14974 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.191014.001 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: olive
Device model: Redmi 8
Device product name: olive

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MankMeo** [comment]
Solution: Reset user strings, and it works!
