### ISSUE TITLE
Cubari: Latest doesn't work

### ISSUE THREAD

**Issue by wsu808** [tachiyomiorg/tachiyomi-extensions#13937]
### Source information and language

Cubari 1.3.15 (all)

### Steps to reproduce

1. Browse → Sources → Cubari
2. Enter WebView and login on the bottom of the page
3. go back and click **Latest** tab

### Expected behavior

There is reading history displayed

### Actual behavior

No series are displayed

### Tachiyomi version

TachiyomiSY 1.8.5 (Based on Tachiyomi stable 0.13.6)

### Android version

Android 12

### Other details

Latest tab works fine on 1.3.14, issue appeared when I updated extension to 1.3.15
I tried loging out and in again and clearing cache.
History in webview displays correctly.

Also pinning series in cubari should make it appear in **Popular** tab. It doesn't work either.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment]
Probably not very helpful, but this is what I get through logcat:
```
2022-10-21 19:11:57.772 10962-10962/? E/LatestUpdatesController: java.lang.NullPointerException
        at eu.kanade.tachiyomi.extension.all.cubari.Cubari.parseManga(Cubari.kt:354)
        at eu.kanade.tachiyomi.extension.all.cubari.Cubari.parseManga$default(Cubari.kt:347)
        at eu.kanade.tachiyomi.extension.all.cubari.Cubari.parseMangaList(Cubari.kt:328)
        at eu.kanade.tachiyomi.extension.all.cubari.Cubari.latestUpdatesParse(Cubari.kt:65)
        at eu.kanade.tachiyomi.extension.all.cubari.Cubari.fetchLatestUpdates$lambda-1(Cubari.kt:60)
        at eu.kanade.tachiyomi.extension.all.cubari.Cubari.$r8$lambda$YQ0Y1_l8S2TwxvC9U9l1SMl8-mQ(Unknown Source:0)
        at eu.kanade.tachiyomi.extension.all.cubari.Cubari$$ExternalSyntheticLambda5.call(Unknown Source:4)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:1)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:3)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:4)
        at rx.Subscriber.setProducer(Subscriber.java:8)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1)
        at rx.Subscriber.setProducer(Subscriber.java:6)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(R8$$SyntheticClass:5)
        at rx.Observable.unsafeSubscribe(Observable.java:2)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
        at rx.Observable.unsafeSubscribe(Observable.java:2)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
        at rx.Observable.subscribe(Observable.java:25)
        at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:4)
        at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:1)
        at eu.kanade.tachiyomi.ui.browse.source.latest.LatestUpdatesPager.requestNextPage(LatestUpdatesPager.kt:4)
        at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
     Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:5)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:3) 
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:4) 
        at rx.Subscriber.setProducer(Subscriber.java:8) 
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1) 
        at rx.Subscriber.setProducer(Subscriber.java:6) 
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(R8$$SyntheticClass:5) 
        at rx.Observable.unsafeSubscribe(Observable.java:2) 
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2) 
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1) 
        at rx.Observable.unsafeSubscribe(Observable.java:2) 
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4) 
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1) 
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4) 
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1) 
        at rx.Observable.subscribe(Observable.java:25) 
        at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:4) 
        at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:1) 
        at eu.kanade.tachiyomi.ui.browse.source.latest.LatestUpdatesPager.requestNextPage(LatestUpdatesPager.kt:4) 
        at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18) 
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2) 
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10) 
```
