### ISSUE TITLE
Baozinmh: Causes the app to crash

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi-extensions#14317]
### Source information and language

Zh.baozimh.org 1.3.27 (中文）

### Steps to reproduce

Clicked in to extension and tachiyomi will forced close

### Expected behavior

Able to browse

### Actual behavior

Application lagged out and force closed

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do provide crash logs if the extension is making the app to crash, otherwise it will be pretty difficult to figure out the root cause.

**Comment by stevenyomi** [comment]
```
kotlin.UninitializedPropertyAccessException: lateinit property url has not been initialized
	at eu.kanade.tachiyomi.source.model.SMangaImpl.getUrl(SMangaImpl.kt:9)
	at eu.kanade.domain.manga.model.MangaKt.toDomainManga(Manga.kt:19)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$getMangaList$1$2$1$1.invokeSuspend(BrowseSourcePresenter.kt:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [LazyStandaloneCoroutine{Cancelling}@7a300f, Dispatchers.Main]
```

**Comment by Bishopop6** [comment]
Crash example screen record.

**Comment by stevenyomi** [comment]
The site changed its theme from Madara/WPManga + Elementor to GeneratePress, its mirror to Blocksy Child.

**Comment by Bishopop6** [comment]
Is there a way to fix it? Or the extension is down?

**Comment by stevenyomi** [comment]
> Is there a way to fix it?

Yes but I'll take a look at it later.
