### ISSUE TITLE
baozimanhua: fetchPageList failed when no page number

### ISSUE THREAD

**Issue by rhjdvsgsgks** [tachiyomiorg/tachiyomi-extensions#17406]
### Source information

1.4.20

### Source language

chinese

### Steps to reproduce

open https://cn.czmanga.com/comic/chapter/wolaiziyouxi-mokf_c/0_200.html

### Expected behavior

able to show the manga

### Actual behavior

```
java.lang.NumberFormatException: For input string: ""
       at java.lang.Integer.parseInt(Integer.java:627)
       at java.lang.Integer.parseInt(Integer.java:650)
       at eu.kanade.tachiyomi.extension.zh.baozimanhua.Baozi.fetchPageList$lambda$10(Baozi.kt:146)
       at eu.kanade.tachiyomi.extension.zh.baozimanhua.Baozi.$r8$lambda$kIYsXUDv4mdBNSa67HPRf3ChmnA(Unknown Source:0)
       at eu.kanade.tachiyomi.extension.zh.baozimanhua.Baozi$$ExternalSyntheticLambda2.call(Unknown Source:4)
       at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:4)
       at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:1)
       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
       at rx.Observable.subscribe(Observable.java:25)
       at tachiyomi.core.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:28)
       at eu.kanade.tachiyomi.source.online.HttpSource.getPageList(HttpSource.kt:5)
       at eu.kanade.tachiyomi.ui.reader.loader.HttpPageLoader.getPages(HttpPageLoader.kt:84)
       at eu.kanade.tachiyomi.ui.reader.loader.ChapterLoader$loadChapter$2.invokeSuspend(ChapterLoader.kt:88)
       at eu.kanade.tachiyomi.ui.reader.loader.ChapterLoader$loadChapter$2.invoke(ChapterLoader.kt:13)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
       at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
       at tachiyomi.core.util.lang.CoroutinesExtensionsKt.withIOContext(CoroutinesExtensions.kt:5)
       at eu.kanade.tachiyomi.ui.reader.loader.ChapterLoader.loadChapter(ChapterLoader.kt:34)
       at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.access$loadChapter(ReaderViewModel.kt:78)
       at eu.kanade.tachiyomi.ui.reader.ReaderViewModel$init$2.invokeSuspend(ReaderViewModel.kt:212)
       at eu.kanade.tachiyomi.ui.reader.ReaderViewModel$init$2.invoke(ReaderViewModel.kt:13)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
       at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
       at tachiyomi.core.util.lang.CoroutinesExtensionsKt.withIOContext(CoroutinesExtensions.kt:5)
       at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.init-0E7RQCE(ReaderViewModel.kt:83)
       at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onCreate$1.invokeSuspend(ReaderActivity.kt:52)
       at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onCreate$1.invoke(ReaderActivity.kt:13)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
       at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
       at tachiyomi.core.util.lang.CoroutinesExtensionsKt$launchNonCancellable$1.invokeSuspend(CoroutinesExtensions.kt:31)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
```

baozi.kt:146 should be line 145 in official extension ([this line](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/15d527bac96931cfd06db0132ed3a4bbb3a9ce55/src/zh/baozimanhua/src/eu/kanade/tachiyomi/extension/zh/baozimanhua/Baozi.kt#L145))

### Tachiyomi version

0.14.6

### Android version

android 11

### Other details

it only affect few of chapter.

it caused by these chapter dont have page number like "1/50" in the value of amp-img .

maybe we can use id of amp-img to calculate page number as a fallback

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by derbysig** [comment]
it is affecting all the titles that I am reading from baozimanhua.
