### ISSUE TITLE
Installed but not installed

### ISSUE THREAD

**Issue by NickSei** [tachiyomiorg/tachiyomi-extensions#17988]
### Source information

Flamescans 1.4.30 and Hiperdex 1.4.41

### Source language

English

### Steps to reproduce

Open tachiyomi > go to browse >  extensions

### Expected behavior

Installed app should stay installed

### Actual behavior

Extension does not stay installed even installing it in the app. 

### Tachiyomi version

R6049

### Android version

Android 8.0

### Other details

![Screenshot_2023-09-17-00-10-08-73](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/68117224/38ab6514-ca3c-4d5c-9e1b-469ecbb42655)
![Screenshot_2023-09-17-00-08-35-32](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/68117224/3c1887a8-eaf5-4527-a735-f3d93b728fe0)
![Uploading Screenshot_2023-09-17-00-08-54-22.png…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Whoopee4954** [comment]
Got the same issue
/

**Comment by Whoopee4954** [comment]
[1695031821106_1694767253745_tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/12646615/1695031821106_1694767253745_tachiyomi_crash_logs.txt)
Problem seems to be only existing in preview release. In stable, extension works as expected.

**Comment by NickSei** [comment]
Rollback to version r6027 is work around that i found for the mean time, which enables the extensions that I experienced having troubles.

**Comment by arkon** [comment]
```

09-15 10:38:28.682 26320 26320 E ExtensionLoader: Extension load error: Flame Scans (eu.kanade.tachiyomi.extension.all.flamescans.FlameScansFactory)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: java.lang.NoClassDefFoundError: Failed resolution of: Leu/kanade/tachiyomi/extension/all/flamescans/FlameScans;
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtension(SourceFile:498)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.access$loadExtension(SourceFile:1)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at eu.kanade.tachiyomi.extension.util.ExtensionLoader$loadExtensions$1$deferred$1$1.invokeSuspend(SourceFile:12)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:169)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:31)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:77)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:7)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtensions(SourceFile:153)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at eu.kanade.tachiyomi.extension.ExtensionManager.<init>(SourceFile:123)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at eu.kanade.tachiyomi.AppModule$registerInjectables$11.invoke(SourceFile:9)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(SourceFile:5)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlin.SynchronizedLazyImpl.getValue(SourceFile:21)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(SourceFile:49)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(SourceFile:16)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at eu.kanade.tachiyomi.AppModule$registerInjectables$10.invoke(SourceFile:20)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(SourceFile:5)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at kotlin.SynchronizedLazyImpl.getValue(SourceFile:21)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(SourceFile:49)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(SourceFile:16)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at eu.kanade.tachiyomi.AppModule.$r8$lambda$0RHLTm-bvsDpST_-bhuVCJga1ss(SourceFile:27)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at androidx.work.CoroutineWorker$$ExternalSyntheticLambda0.run(SourceFile:1)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at android.os.Handler.handleCallback(Handler.java:873)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at android.os.Looper.loop(Looper.java:216)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at android.app.ActivityThread.main(ActivityThread.java:7266)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: Caused by: java.lang.ClassNotFoundException: eu.kanade.tachiyomi.extension.all.flamescans.FlameScans
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	... 33 more
09-15 10:38:28.682 26320 26320 E ExtensionLoader: Caused by: java.lang.IllegalAccessError: Method 'android.content.SharedPreferences eu.kanade.tachiyomi.extension.all.flamescans.FlameScans.getPreferences()' implementing interface method 'android.content.SharedPreferences eu.kanade.tachiyomi.source.ConfigurableSource.getPreferences()' is not public (declaration of 'eu.kanade.tachiyomi.extension.all.flamescans.FlameScans' appears in /data/app/eu.kanade.tachiyomi.extension.all.flamescans-uvMW7XcDusNAa_CaAy-5Jw==/base.apk)
09-15 10:38:28.682 26320 26320 E ExtensionLoader: 	... 33 more
```
