### ISSUE TITLE
[Toonily] Download and viewing of chapters posted in the last 24 hours are broken (10/27/2023)

### ISSUE THREAD

**Issue by serveral1** [tachiyomiorg/tachiyomi-extensions#18760]
### Source information

Toonily 1.4.42

### Source language

English

### Steps to reproduce

1. Open any title from the source
2. Attempt to download/read any chapter from a title that has had an update in the last 24 hours
3. Get "Image could not be loaded" error
4. Attempt to do the same with an older chapter (uploaded before the 27th/26th of October)
5. No download/reading error happens.

### Expected behavior

All chapters to be downloaded correctly without any issues.

### Actual behavior

Images from the most recent downloaded chapters are broken. Other image viewers also indicate that the downloaded images are corrupted.

### Tachiyomi version

0.14.7

### Android version

Android 10

### Other details

The chapters on the website itself don't seem to be broken and can be viewed without any issues. I did however check on their discord channel and some users have reported issues with cloudflare in the past 24 hours. What I find most odd is that the issue can only be replicated when downloading/viewing said chapters that have been uploaded in the last 24 hours, as downloading older chapters seems to work fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
broken images on the site: ![tmp](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/48650614/825b1dfd-ec10-4e8a-a870-5cd87e0907ff)
```
 W  Failed to find image type
 E  No decoder found to handle this stream
 E  Failed to initialise bitmap decoder
                 java.lang.Exception: Image decoder failed to initialize and get image size
                 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(SourceFile:67)
                 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:8)
                 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:1)
                 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by ElCacciatore** [comment]
Sorry, i didn't see your post. Admin can delete mine and keep yours. I got thé same problèm with new Chapter.

**Comment by JowMK** [comment]
Similar problem here, i discovered that cloudflare is blocking access to the image server. If i click in the open in webview button of the image in the reader, last night i would have gotten a cloudflare blocked page, telling me to contact the owners of the page, but toonily told me back that this is not their issue, but now i can see the images perfecly using the webview button in the reades (the "image could not be loaded" one) but still does not download nor show the image in the reader
