### ISSUE TITLE
[Bug] <copymanga extension>: <漫画的详情页崩溃>

### ISSUE THREAD

**Issue by houfukude** [tachiyomiorg/tachiyomi-extensions#5573]
## Device information

- Tachiyomi version: 0.10.7 and 0.10.7.3045
- Android version: 7.1.1

## Source information

- Name: copymanga extension
- Extension version: v1.2.4

## Steps to reproduce

1. First Step
      浏览 -> 图源 ->拷贝漫画
2. Second Step
      点击任意漫画，在详情页面载入章节列表的时候崩溃
### Expected behavior
      章节列表载入完成

### Actual behavior

      章节列表载入过程中整个应用崩溃并返回桌面

## Other details

1.  此问题只出现于 FUJITSU F-04H 平板上，更换设备（pixel2xl ,Redmi 7A）并未出现此问题
2.  尝试更换 应用 以及系统设置的时间格式均无果
3.  不知道preview版本从什么时候开始不再输出崩溃日志了，只弹出一个 Toast ，因此用的 `0.10.7` 抓取日志
4.  以下是崩溃时出现的错误日志
```LOG
2021-01-28 00:32:55.998 20774-20818/? E/ACRA: ACRA caught a IllegalStateException for eu.kanade.tachiyomi
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
        at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga.stringToUnixTimestamp(CopyManga.kt:350)
        at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga.stringToUnixTimestamp$default(CopyManga.kt:349)
        at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga.chapterListParse(CopyManga.kt:126)
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchChapterList$1.call(HttpSource.kt:214)
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchChapterList$1.call(HttpSource.kt:26)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:30)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber$1.request(OperatorSubscribeOn.java:109)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.setProducer(OperatorSubscribeOn.java:105)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:50)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:18)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.format.DateTimeFormatter" on path: DexPathList[[zip file "/data/app/eu.kanade.tachiyomi.extension.zh.copymanga-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga.stringToUnixTimestamp(CopyManga.kt:350) 
        at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga.stringToUnixTimestamp$default(CopyManga.kt:349) 
        at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga.chapterListParse(CopyManga.kt:126) 
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchChapterList$1.call(HttpSource.kt:214) 
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchChapterList$1.call(HttpSource.kt:26) 
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) 
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101) 
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:30) 
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber$1.request(OperatorSubscribeOn.java:109) 
        at rx.Subscriber.setProducer(Subscriber.java:211) 
        at rx.Subscriber.setProducer(Subscriber.java:205) 
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) 
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.setProducer(OperatorSubscribeOn.java:105) 
        at rx.Subscriber.setProducer(Subscriber.java:205) 
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) 
        at rx.Subscriber.setProducer(Subscriber.java:205) 
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:50) 
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:18) 
        at rx.Observable.unsafeSubscribe(Observable.java:10327) 
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) 
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) 
        at rx.Observable.unsafeSubscribe(Observable.java:10327) 
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
        at rx.Observable.unsafeSubscribe(Observable.java:10327) 
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) 
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) 
        at rx.Observable.unsafeSubscribe(Observable.java:10327) 
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) 
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) 
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by arkon** [comment]
Duplicate of #5544
