### ISSUE TITLE
[Bug] tachiyomi : download queue crash, dup dir source name renaming on  create

### ISSUE THREAD

**Issue by Wyld-One** [tachiyomiorg/tachiyomi-extensions#6619]
## Device information
- Tachiyomi v10.10
- id version: 9

## Source information
- Name: Read Nanatsu no taizai/7 Deadly Sins Manga Online (EN)
- Extension version: ?
newest

## Steps to reproduce
1. First Step
2. Second Step

1 select source
2 select 7 deadly sins
3 favorite (heart)
4 download all chapters

### Expected behavior
Describe what should have happened
downloads all chapters to single dir

### Actual behavi
Describe what happens instead

queue crashes after 33 chapters downloaded. 

## Other details

download dir was on SD external card

after short debug, found multiple renamed dir of the source name with one chapter in each.

rename is a feature of android to avoid saving over same named files

suspect source name too long

crash report:

--------- beginning of main
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: Failed to createFile
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: Failed to createFile
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: Failed to createFile
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: Failed to createFile
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: Failed to createFile
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
[tachiyomi_crash_logs.txt]

**Comment by arkon** [comment]
Does it happen consistently with specific chapters?

**Comment by Wyld-One** [comment]
yes. if i remove the dup dirs and clear queue . restart download of all . it will again stop after 33 chapters. you get chapers 1-33

also if del dirs and just reseme queue, it will again stop after 33chapters. however; this time the chapters saved will start where it left off. eg chapters 33-66

note: queue is set to order by ascendings chapters first - how i found it - i had fiddled with order, and found a temp workaround.

even delete/add of that specific source and manga caused queue crash

this might effect any source depending on just where this code is located(main/each extention)

**Comment by Wyld-One** [comment]
btw, i am a vet programmer of 35yrs. I've seen some odd stuff

**Comment by arkon** [comment]
I meant if it's consistent with a specific chapter in isolation. It may have to do with the path that it's attempting to create.

**Comment by Wyld-One** [comment]
chapter does not matter,.
path does.

**Comment by Wyld-One** [comment]
may have to escalate. so same behavior on another extension different path depth. will enclose snapshot. 
![Screenshot_20210421-214048](https://user-images.githubusercontent.com/16184762/115653810-19478b00-a2ed-11eb-899d-94ac4f8c55e9.png)

**Comment by Wyld-One** [comment]
tested:
two phones -moto z3(android id 9), samsung galaxy s7(android 8)

two seperate new Sd cards


another (3rd) ext source found: Boku no Hero Academia

same thing - if more than 34 chapters downloaded per manga ,dir will auotrename then queue will crash

**Comment by arkon** [comment]
> may have to escalate.

Escalate to who?

> same thing - if more than 34 chapters downloaded per manga ,dir will auotrename then queue will crash

The root issue here is that the name's casing changed, which is resulting in the duplicate suffixed folders. It should be fine if you just rename the first folder to match what the name currently is. Android itself crashing because of attempting to create a folder is a bit unfortunate, but I'm not surprised.

I can attempt to make the check for these folders case insensitive as well.

**Comment by Wyld-One** [comment]
Interesting bit, there are two (same source & manga) with different
cases(upper/lower)

**Comment by Wyld-One** [comment]
I might have clue to problem.

both sources that produce this error have a forward slash in the name. is it possible that the slash is not being properly sanitized before the fall is created?
