### ISSUE TITLE
Mangachan: Chapter selector changed

### ISSUE THREAD

**Issue by simakover** [tachiyomiorg/tachiyomi-extensions#8948]
### Source information

Mangachan 1.2.9

### Steps to reproduce

1. open manga
2. refresh chapters
3. get error

### Expected behavior

loaded chapters

### Actual behavior

error

### Tachiyomi version

preview r0

### Android version

MIUI 12

### Other details

E/StandaloneCoroutine: 	├ exh.log.LoggingKt.xLogE(Logging.kt:20)
    	├ eu.kanade.tachiyomi.ui.manga.MangaPresenter$fetchMangaFromSource$1.invokeSuspend(MangaPresenter.kt:322)
    	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    	├ kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    	├ kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    	├ kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    	└ kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
    Error getting manga details
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference
        at eu.kanade.tachiyomi.extension.ru.mangachan.Mangachan.mangaDetailsParse(Mangachan.kt:180)
        at eu.kanade.tachiyomi.source.online.ParsedHttpSource.mangaDetailsParse(ParsedHttpSource.kt:137)
        at eu.kanade.tachiyomi.source.online.HttpSource.fetchMangaDetails$lambda-5(HttpSource.kt:213)
        at eu.kanade.tachiyomi.source.online.HttpSource.$r8$lambda$VfbGQ4_rQeJEmXM5gOo1sDE66nQ(Unknown Source:0)
        at eu.kanade.tachiyomi.source.online.HttpSource$$ExternalSyntheticLambda3.call(Unknown Source:4)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:37)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda-0(OkHttpExtensions.kt:57)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.$r8$lambda$V4FTlhE0zGLykdl_yqVQNonk7gs(Unknown Source:0)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(Unknown Source:4)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:25)
        at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:21)
        at eu.kanade.tachiyomi.source.Source$DefaultImpls.getMangaDetails(Source.kt:68)
        at eu.kanade.tachiyomi.source.CatalogueSource$DefaultImpls.getMangaDetails(CatalogueSource.kt:7)
        at eu.kanade.tachiyomi.source.online.HttpSource.getMangaDetails(HttpSource.kt:33)
        at eu.kanade.tachiyomi.ui.manga.MangaPresenter$fetchMangaFromSource$1.invokeSuspend(MangaPresenter.kt:313)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
    Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me

**Comment by Riztard** [comment]
not related but ok

**Comment by Riztard** [comment]
> work for me

just close it, as i already said before its working and no respond
